version: '2'

services:
  # App backend service
  bug-service:
    # Configuration for building the docker image for the backend service
    build:
      dockerfile: Dockerfile
    ports:
      - "8181:8181" # Forward the exposed port 8080 on the container to port 8081 on the host machine
    restart: always
    depends_on:
      - mysql # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reporting
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: create
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Networks to be created to facilitate communication between containers
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: reporting
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
