spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: jdbc:mysql://mysql/reporting
    password: ${DB_PASSWORD}

  jpa:

    database: mysql
    hibernate:
      ddl-auto: create
server:
  port: '8282'
